### PR TITLE
lastchildistrivia fix

### LINKED ISSUE #243: String span/fullspan off by 1 vs version 2 CSTParser
on master

```
julia> str = "\"some long title \$label1 \$label2\" a"
"\"some long title \$label1 \$label2\" a"

julia> x = CSTParser.parse(str)
  1:35  macrocall
  1:0    globalrefdoc
  1:0    NOTHING: nothing
  1:34   string
  1:17    STRING: some long title
 18:23    label1
 24:24    STRING:
 25:30    label2
 35:35   a

julia> a = x[3]
  1:34  string
  1:17   STRING: some long title
 18:23   label1
 24:24   STRING:
 25:30   label2

julia> a.span
34

julia> a.fullspan
34
```

on v2.5

```
julia> x = CSTParser.parse(str)
  1:35  MacroCall
  1:0    GlobalRefDoc
  1:34   StringH
  1:17    STRING: some long title
 18:24    UnaryOpCall
 18:18     OP: EX_OR
 19:24     label1
 25:25    STRING:
 26:32    UnaryOpCall
 26:26     OP: EX_OR
 27:32     label2
 33:34    STRING:
 35:35   a


julia> a = x[2]
  1:34  StringH
  1:17   STRING: some long title
 18:24   UnaryOpCall
 18:18    OP: EX_OR
 19:24    label1
 25:25   STRING:
 26:32   UnaryOpCall
 26:26    OP: EX_OR
 27:32    label2
 33:34   STRING:


julia> a.span
33

julia> a.fullspan
34

```

### PR DESCRIPTION
**Pull request by ZacLN**
closes #243

### CODE REVIEW

File: test/parser.jl [hunk 1]
```diff
@@ -896,6 +896,11 @@ end""" |> test_expr
...
     end
     @testset "bad uint" begin
-            @test Expr(CSTParser.parse("0x.")) == Expr(:error)
-        end
+        @test Expr(CSTParser.parse("0x.")) == Expr(:error)
+    end
+
+    @testset "endswithtrivia" begin
+        x = CSTParser.parse(raw""""some long title $label1 $label2"  a""")
+        @test CSTParser.lastchildistrivia(x[3])
```
Comment (pfitzseb) [inline test/parser.jl:904]: Might be good to have a test for `x[3].span < x[3].fullspan` here, if I understand this correctly.

Comment (ZacLN) [reply test/parser.jl:905]: You understand correctly - that is what it's testing via `lastischildistrivia`, but I've added another explicit test

**Review by pfitzseb — APPROVED** [review]

**Review by davidanthoff — APPROVED** [review]
