### PR TITLE
Fix quoted nonstd ids (:var"sdf"), fix inf-loop check

### LINKED ISSUE #198: Parsing error on :var"name"
Got to this from JuliaFormatter, trying to format this line: https://github.com/KristofferC/TOMLX.jl/blob/4646119c785f529d59c303ad113dc43be46b9c36/src/parser.jl#L152

I see `var"name"` support was added in #118, but this seems to be an edge case:

```julia
julia> using CSTParser

julia> :var"name"
:name

julia> :(var"name")
:name

julia> :(r"name")
:(r"name")

julia> :r"name"  # for normal string macros this is invalid
ERROR: syntax: extra token """ after end of expression
Stacktrace:
 [1] top-level scope at none:1

julia> CSTParser.parse(":(var\"name\")")
  1:12  Quote
  1:1    OP: COLON
  2:12   InvisBrackets
  2:2     (
  3:11    name
 12:12    )


julia> CSTParser.parse(":var\"name\"")
  1:10  ErrorToken
  1:4    Quotenode
  1:1     OP: COLON
  2:4     var
  5:10   STRING: name
```

### PR DESCRIPTION
**Pull request by ZacLN**
Fix #198 (parse error for quoted non standard symbols,  `:var"something"`).

Also fixes a loop check to allow comma separated lists of > 10000 elements.

### CODE REVIEW

File: src/components/operators.jl [hunk 1]
```diff
@@ -203,12 +203,21 @@ function parse_unary_colon(ps::ParseState, op::EXPR)
...
+            id = EXPR(NONSTDIDENTIFIER, EXPR[id, arg])
+        end
+        ret = EXPR(Quotenode, EXPR[op, id])
     elseif Tokens.begin_literal < kindof(ps.nt) < Tokens.CHAR ||
         isoperator(kindof(ps.nt)) || isidentifier(ps.nt) || kindof(ps.nt) === Tokens.TRUE || kindof(ps.nt) === Tokens.FALSE
         ret = EXPR(Quotenode, EXPR[op, INSTANCE(next(ps))])
     elseif closer(ps)
         ret = op
     else
+        @info 1
```
Comment (visr) [inline src/components/operators.jl:220]: looks like this was left in by accident

Comment (ZacLN) [reply src/components/operators.jl]: Yep, removed
